### ISSUE TITLE
应用体验排查

### ISSUE THREAD

**Issue by anycodes** [devsapp/awesome#1]
- Hello World（西流+千风）
  - [x] fc-http-node.js6
  - [x] fc-http-node.js8
  - [x] fc-http-node.js10
  - [x] fc-http-node.js12
  - [x] fc-http-php7.2
  - [x] fc-http-python2.7
  - [x] fc-http-python3.6
  - [x] fc-http-java8
  - [x] fc-event-node.js6
  - [x] fc-event-node.js8
  - [x] fc-event-node.js10
  - [x] fc-event-node.js12
  - [x] fc-event-php7.2
  - [x] fc-event-python2.7
  - [x] fc-event-python3.6
  - [x] fc-event-java8
  - [x] Golang example
  - [x] Nodejs10 example
  - [x] Nodejs12 example
  - [x] PHP74-Swoole
  - [x] Python37 Event函数
  - [x] Python37 HTTP函数
  - [x] C++ Event函数
  - [x] C++ HTTP函数
  - [x] Java8-SpringBoot
  - [x] Ruby example
  - [x] Powershell example
  - [x] F# example
  - [x] TypeScript example
  - [x] Lua example
  - [x] Dart example
  - [x] Rust example
  - [x] C++ Event函数
  - [x] Node.js 14 Event函数
  - [x] Python3.9 Event函数
  - [x] C++ HTTP函数
  - [x] Springboot HTTP函数
  - [x] ASP.Net Core HTTP函数
- Web Framework（寒斜+丹坤）
  - [x] 普通静态资源应用: s init website-base
  - [x] react应用 s init website-react
  - [x] vue应用 s init website-vue
  - [x] hexo应用 s init website-hexo
  - [x] docusaurus应用 s init website-docusaurus
  - [x] vuepress应用 s init website-vuepress
  - [x] nuxt-ssr: s init start-nuxt-ssr
  - [x] nuxt-spa: s init start-nuxt-spa
  - [x] Egg [custom]
  - [x] Express [custom]
  - [x] Hapi [custom]
  - [x] Koa [custom]
  - [x] Next [custom]
  - [x] Nuxt [custom]
  - [x] Nest [custom]
  - [x] Think.js [custom]
  - [x] Connect [custom]
  - [x] Bottle [python3]
  - [x] Django [python3]
  - [x] Flask [python3]
  - [x] Pyramid [python3]
  - [x] Tornado [custom]
  - [x] Webpy [python3]
  - [x] ThinkPHP
  - [x] Laravel
  - [x] Wordpress
  - [x] Z-BlogPHP
  - [x] Discuz
  - [x] Echsop
  - [x] Metinfo
  - [x] Typecho
  - [x] Whatsns
  - [x] Springboot
- 场景化（刘禅+封崇）
  - AI场景
    - [x] PyTorch案例 s init start-pytorch
    - [x] Tensorflow案例 s init start-tensorflow
    - [x] OCR案例 s init start-ocr
    - [x] 目标检测案例 s init image-prediction-app
  - 音视频处理场景
    - [x] 弹性高可用的高度自定义音视频处理: s init ffmpeg-app
    - [x] 对直播视频流截图的应用: s init rtmp-snapshot
    - [x] 一个对浏览器全景录制: s init headless-ffmpeg
  - 数据库链接场景
    - [x] mysql案例: s init start-fc-mysql-python
    - [x] redis案例: s init start-fc-redis-python
    - [x] mongodb案例: s init start-fc-mongodb-python
    - [x] sql-server案例: s init start-fc-sql-server-python
    - [x] postgresql案例: s init start-fc-postgresql-python
    - [x] Lindorm案例: s init start-fc-lindorm-python
  - 其他场景
    - [x] 基于Node.js的案例: s init puppeteer-nodejs
    - [x] 基于Container的案例: s init puppeteer-container
    - [x] word转pdf的应用: s init start-word2pdf
    - [x] pdf转图片的应用: s init start-pdf2img
    - [x] 电商后端管理系统: s init start-fc-mall-admin
    - [x] 现代应用解决方案: s init modern-web-application

**Comment by hanxie-crypto** [comment]
可以增加web应用开发场景，数据库链接拿出来

**Comment by anycodes** [comment]
以下内容通过浏览器打开测试域名会默认下载文件，需要调整一下变成能打开页面的
@wss-git @rsonghuster  

- [x] fc-http-node.js6
- [x] fc-http-node.js8
- [x] fc-http-node.js10
- [x] fc-http-node.js12
- [x] fc-http-php7.2
- [ ] C++ HTTP函数(custom)

**Comment by hryang** [comment]
nodejs 6 和 8 取消了吧，这两个 runtime 都已经过了维护期了。

**Comment by anycodes** [comment]
以下案例，需要考虑是否将一些额外操作放在pre-deploy中，例如：
- [x] fc-http-java8
- [x] fc-event-java8
- [x] Golang example

**Comment by anycodes** [comment]
@wss-git 

- [x] HAPI 

HAPI报错：

http://hapi.web-framework.1583208943291465.cn-beijing.fc.devsapp.net/

```
{"ErrorCode":"CAExited","ErrorMessage":"The function either cannot be started or exited:ContainerStartDuration:120753607558. CA process cannot be started or exited already: rpc error: code = 106 desc = ContainerStartDuration:120000000000. Ping CA failed due to: dial tcp 21.0.1.179:9000: i/o timeout"}
```

**Comment by anycodes** [comment]
- [x]  Nuxt [custom] 的pre-hook是next的，需要修改

**Comment by anycodes** [comment]
- [x] Nodejs10 example 的文档有问题，不需要`cd code`

**Comment by anycodes** [comment]
- [ ] Nodejs10 example

```
Duration: 3.15 ms, Billed Duration: 4 ms, Memory Size: 1024 MB, Max Memory Used: 44.04 MB
========= FC invoke Logs end =========

FC Invoke Result:
SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (<anonymous>)
    at app.post (/code/server.js:30:10)
    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
    at next (/code/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/code/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
    at /code/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/code/node_modules/express/lib/router/index.js:335:12)
    at next (/code/node_modules/express/lib/router/index.js:275:10)
    at /code/node_modules/body-parser/lib/read.js:130:5


End of method: invoke
```

**Comment by anycodes** [comment]
- [x] 基于Node.js的案例: s init puppeteer-nodejs

```
{
  "errorMessage": "Cannot find module 'puppeteer'\nRequire stack:\n- /code/index.js\n- /var/fc/runtime/nodejs12/src/prepare_code.js\n- /var/fc/runtime/nodejs12/src/invoke.js\n- /var/fc/runtime/nodejs12/src/server.js",
  "errorType": "Error",
  "stackTrace": [
    "Error: Cannot find module 'puppeteer'",
    "Require stack:",
    "- /code/index.js",
    "- /var/fc/runtime/nodejs12/src/prepare_code.js",
    "- /var/fc/runtime/nodejs12/src/invoke.js",
    "- /var/fc/runtime/nodejs12/src/server.js",
    "at Module._resolveFilename (internal/modules/cjs/loader.js:982:15)",
    "at Module._load (internal/modules/cjs/loader.js:864:27)",
    "at Module.require (internal/modules/cjs/loader.js:1044:19)",
    "at require (internal/modules/cjs/helpers.js:77:18)",
    "at (/code/index.js:2:19)",
    "at Module._compile (internal/modules/cjs/loader.js:1158:30)",
    "at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)",
    "at Module.load (internal/modules/cjs/loader.js:1002:32)",
    "at Module._load (internal/modules/cjs/loader.js:901:14)",
    "at Module.require (internal/modules/cjs/loader.js:1044:19)"
  ]
}
```

**Comment by anycodes** [comment]
- [x] hexo应用 s init website-hexo

@heimanba 

![image](https://user-images.githubusercontent.com/21079031/144973643-bced8f0b-e942-40f0-9e52-c2b12ba927f2.png)

http://anycodes-website-hexo.oss.devsapp.net/

> 原因dns解析还没生效

**Comment by anycodes** [comment]
- [ ] ASP.Net Core HTTP函数（container）

http://aspdotnetcore-http-function.hello-world-service.1583208943291465.cn-hangzhou.fc.devsapp.net/

![image](https://user-images.githubusercontent.com/21079031/144976763-60d452da-dca0-4a1b-9786-869904f8a811.png)

**Comment by anycodes** [comment]
- [ ] C++ HTTP函数（container）

![image](https://user-images.githubusercontent.com/21079031/144982040-4d3a3643-8507-47c2-949a-7102e25f7e7a.png)


http://cpp-http-function.hello-world-service.1583208943291465.cn-hangzhou.fc.devsapp.net/


这个貌似不是很友好

**Comment by anycodes** [comment]
- [x] 基于Express框架的todoList应用：s init todolist-app

- [x] 基于Django框架的博客应用：s init django-blog

**Comment by anycodes** [comment]
- [x] connect案例需要完善
- [x] thinkjs案例需要完善

![image](https://user-images.githubusercontent.com/21079031/144983058-ccc97275-5e00-4cf3-9d5d-4270364a29c4.png)

需要替换为`srtart-connect`

**Comment by liulang0817** [comment]
- [ ] PyTorch案例 s init start-pytorch

![image](https://user-images.githubusercontent.com/38310830/144993994-20287ea2-19e2-4b84-b11c-f79d65c5bb30.png)
PyTorch案例执行 s build --use-docker --dockerfile ./code/Dockerfile 报错

**Comment by anycodes** [comment]
- [x] 基于函数计算的红白机游戏: s init fc-nes-game
- [x] 基于函数计算的盲盒游戏: s init blindbox-game
- [x] 创意活动Jamsatck站点: s init start-jamstack-activities
- [x] Serverless架构的弹幕应用: s init tart-barrage

**Comment by liulang0817** [comment]
- [x] OCR案例 s init start-ocr

OCR案例执行s local start auto 失败，部署到线上执行成功
![image](https://user-images.githubusercontent.com/38310830/145003629-ecd2a1cd-e96e-4ed3-9a76-9af1baac2caa.png)
![image](https://user-images.githubusercontent.com/38310830/145003768-48e430a2-4efa-46fb-a82d-108dbd748f91.png)
![image](https://user-images.githubusercontent.com/38310830/145003797-d84f5b26-44a2-4974-8501-cbad778d12cd.png)

**Comment by liulang0817** [comment]
- [x] 弹性高可用的高度自定义音视频处理: s init ffmpeg-app

弹性高可用的高度自定义音视频处理: s init ffmpeg-app 可以正常部署执行，但是示例文档建议优化下，部署这里执行这个初始化命令s init ffmpeg -p alibaba 命令报错，找不到-p命令，正常应该是执行快速开始这里的命令，建议可以删除这个部署版块。
![image](https://user-images.githubusercontent.com/38310830/145140881-db740744-1579-441c-a772-fe90aa8de010.png)
![image](https://user-images.githubusercontent.com/38310830/145141120-9126df9c-8caa-4777-8d4d-1c50b676eba9.png)
![image](https://user-images.githubusercontent.com/38310830/145141023-4b00c6a8-9655-44f1-bab4-bcf5f574b89d.png)

**Comment by liulang0817** [comment]
- [x] 一个对浏览器全景录制: s init headless-ffmpeg


执行s deploy --push-registry acr-internet --use-local -y部署报错，提示服务角色没有权限。示例上没有配置角色
![image](https://user-images.githubusercontent.com/38310830/145180458-c2493715-7365-4b93-a10d-b45cffcd83e9.png)
![image](https://user-images.githubusercontent.com/38310830/145180589-f5edd0b9-0434-4f86-91bc-3b5aade1cafc.png)

**Comment by liulang0817** [comment]
- [x]  pdf转图片的应用: s init start-pdf2img

部署执行成功

**Comment by anycodes** [comment]
- [ ] RUST
![image](https://user-images.githubusercontent.com/21079031/145340068-8b3d42be-a186-4bba-8b70-7762d8f342c5.png)
